### PR TITLE
Okazaki - Sample - P1

### PR DESCRIPTION
**Pull request by wwysoc2**

### CODE REVIEW

**Review by clsackett — APPROVED** [review]

**Comment by wteouchicago** [comment]
were "Brain Stem" and "Common Duct" supposed to be deprecated too?

**Comment by bullenc** [comment]
> were "Brain Stem" and "Common Duct" supposed to be deprecated too?

fixed

**Review by ebusygina — APPROVED** [review]
looks good

**Review by wteouchicago — APPROVED** [review]

**Review by stilesj-uchicago — APPROVED** [review]
DICT-511 phase 1 looks good to me.

**Pull request merged**
