### PR TITLE
okazaki p2 OCA updates

### PR DESCRIPTION
**Pull request by bullenc**

### CODE REVIEW

**Review by wwysoc2 — APPROVED** [review]
👍 lgtm!

**Review by ebusygina — APPROVED** [review]

**Review by ProfOak — COMMENTED** [review]
Do we not need to have Parkinson's and dementia in the risk factor section?

**Review by stilesj-uchicago — APPROVED** [review]
Phase 2 looks good.

**Comment by bullenc** [comment]
> Do we not need to have Parkinson's and dementia in the risk factor section?

IMS did not specify these as additions to risk_factors, and they just did a pretty significant comorbidity vs risk_factor assessment recently, so I am guessing for the disease in question (uveal melanoma) that these are not risk factors per se but tend to be mainly comorbidities when the disease shows up (which sounds like in older folks).

**Review by ProfOak — APPROVED** [review]

**Review by wteouchicago — APPROVED** [review]

**Pull request merged**
