### PR TITLE
DAT-214 feat(sample): added non-required link to diagnosis

### PR DESCRIPTION
**Pull request by dmiller15**
r? @allisonheath @msfitzsimons @tlicht3 

Anyone have any better ideas for the "label"?

https://jira.opensciencedatacloud.org/browse/DM-13

### CODE REVIEW

**Comment by tlicht3** [comment]
your'e asking about "diagnoses"? i like it... you're updating what is currently "diagnosis" to allow for more than one diagnosis per case, right?

**Comment by dmiller15** [comment]
No I'm asking about the `label` field in the link. So right now I have `label: related_to`. This field is just for the semantic relation between the nodes. We would say `x sample is related_to y diagnosis`. The field can be anything really. I was just wondering if there was a better word for the relationship: like "derived_from, matched_to, taken_during..."

**Comment by tlicht3** [comment]
oh sorry - it's not really derived from or taken during. the sample was classified with a diagnosis or assigned a diagnosis. related to is good, but are we going to give the a metastatic or recurrent tumor a different diagnosis? if so, related to might be a little broad because it's possible that the diagnosis will be slightly different for a met/recurrent tumor, but they're definitely related to the primary, but that's being awfully specific/literal.  when you create a label do you try to use something that could be used again or can it be specific to the relationship you're describing?

**Comment by dmiller15** [comment]
I would say we aim to be specific with the label. Most of the labels we've come up with so far have been reused, but that has been more the result of not being able to come up with something better.

**Pull request merged**
