### PR TITLE
boveri _terms file split into 2

### PR DESCRIPTION
**Pull request by ganjigajanan**

### CODE REVIEW

**Comment by philtom-ctds** [comment]
at a minimum, you'll need to add the new terms file here to prevent other code from interpreting it as a node:
https://github.com/NCI-GDC/gdcdictionary/blob/develop/gdcdictionary/python/__init__.py#L34-L37

**Review by wteouchicago — APPROVED** [review]
glanced at _terms.yaml and _terms_enum.yaml and looked over most of the <nodes>.yaml files. didn't spot anything out of place.

**Review by wwysoc2 — APPROVED** [review]
lgtm

**Comment by tlicht3** [comment]
@gajanan - why are there only 101,404 additions to the terms_enum file, but 102,446 deletions on the terms file? Did you remove some that aren't being referenced or some other type of clean-up? Really just curious.

**Pull request merged**
