### PR TITLE
feat/masked_methylation_array: initial version

### PR DESCRIPTION
**Pull request by ganjigajanan**
https://jira.opensciencedatacloud.org/browse/DICT-60

### CODE REVIEW

**Review by tlicht3 — APPROVED** [review]
Looks good based on ticket and xlsx 👍

**Review by wteouchicago — COMMENTED** [review]
The masked_methylation_array.yaml looks good to me while comparing it to the raw_methylation_array.yaml file, which it is based on. 

The json file should include the required link to methylation_array_harmonization_workflows -- as discussed in Slack, we can fix it later.

**Comment by wwysoc2** [comment]
Besides the missing link in the JSON, this looks good.  One question though, what's up with the PyYAML line in the requirements file?  It looks like the same thing was deleted and then put back.

**Comment by ganjigajanan** [comment]
> Besides the missing link in the JSON, this looks good. One question though, what's up with the PyYAML line in the requirements file? It looks like the same thing was deleted and then put back.

@wwysoc2, I added the missing link in json now. and in requirement file we added additional package on the 3rd line so essentially we added invisible new line character on PyYAML line that was the change.

**Review by wteouchicago — APPROVED** [review]
The change to json to add link looks good.

**Review by wwysoc2 — APPROVED** [review]

**Review by kulgan — APPROVED** [review]

**Pull request merged**
